# Generated by Django 4.0.5 on 2022-10-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_productcategory_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='productcategory',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_to_children', to='product_module.productcategory', verbose_name='والد'),
        ),
    ]
