# Generated by Django 4.0.5 on 2022-10-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_productcategory_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, unique=True, verbose_name='عنوان در آدرس'),
        ),
    ]
