# Generated by Django 4.0.5 on 2022-10-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productcategory_parent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='والد')),
            ],
            options={
                'verbose_name': 'والد',
                'verbose_name_plural': 'والد',
            },
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent_id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='productcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_to_children', to='product_module.parent'),
        ),
    ]
