# Generated by Django 4.0.5 on 2022-10-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_productcategory_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام استاد')),
                ('pic', models.CharField(max_length=300, verbose_name='تصویر مدرس')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='نوع')),
                ('count', models.CharField(max_length=50, verbose_name='تعداد ویدئوها')),
            ],
            options={
                'verbose_name': 'ویژگی ',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.CharField(max_length=50, null=True, verbose_name='مدت ویدئو'),
        ),
    ]
