# Generated by Django 4.0.5 on 2022-10-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_properties_product_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='product_module.product'),
        ),
    ]
