# Generated by Django 4.0.5 on 2022-10-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_properties_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'متغیر', 'verbose_name_plural': 'متغیر ها'},
        ),
    ]
