# Generated by Django 4.0.5 on 2022-10-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tag', to='product_module.product', verbose_name='محصول'),
        ),
    ]
